name: Test Project
on: push
jobs:
  test:
   runs-on: ubuntu-latest
   steps:
    - name: Print greeting
      run: echo "Hellow World!"
  test2:
   needs: test 
   runs-on: ubuntu-latest
   steps:
    - name: Print ending
      run: echo "The end!"   